### ISSUE TITLE
Fallback between Rss Feed and Atom Feed parser

### ISSUE THREAD

**Issue by MaximRouiller** [dotnet/SyndicationFeedReaderWriter#18]
We should be able to "fallback" on the other parser or identify if a feed is of a certain type or not.

**Comment by jimmyca15** [comment]
@MaximRouiller 

Are you expecting a use case where the type of feed being parsed is not already known?

**Comment by drago-draganov** [comment]
That seems more like application level logic than API requirement. The common layer is the syndication interfaces. Here are my thoughts:

- Factorization of particular interface implementation limits flexibility, especially in low level API.
- Our goal is to offer extensible API. Devs can plug, replace or extend at different levels - reader/parser, writer/formatter because feeds can vary.
- RSS and Atom handling just happens to be in the same library, but these implementations are completely separated.
- Syndication formats are not limited to RSS and Atom only - ex: [JSON Feed](https://jsonfeed.org/). These are likely to be in separate libraries and won't know about each other.
- There are embedded feeds - for instance RSS feed with Atom elements.

**Comment by MaximRouiller** [comment]
Would it be possible to do feed type detection?

Because right now, I have to do the control flow with try/catch. If based on a feedUrl, we could determine that it's RSS 2.0 or Atom 1.0, it would let me pick the right parser. No idea if we can do read ahead or TryRead() ... I don't want to force the API a certain way.

What I have right now is more Exception based control flow while I would prefer to have Feed Type detection to avoid exceptions altogether. 

Thank you so much for the fast responses.

**Comment by drago-draganov** [comment]
SyndicationFeed.ReaderWriter doesn't distinguish where the content comes from (http, file, memory,  etc.). It operates over a valid XmlReader/XmlWriter instance.

Saying that, a well-formatted HTTP Syndication Feed response should represents with a proper Content-Type response header - it's a proper identification for any response type indeed.

Atom feed:
Content-Type: application/atom+xml
[(more info)](https://validator.w3.org/feed/docs/atom.html)

Rss feed:
Content-Type: application/rss+xml
[(more info)](http://www.rssboard.org/rss-mime-type-application.txt)
